services:
    hugo:
        image: klakegg/hugo:latest-ext
        command: serve
        volumes:
            - ".:/src"
        ports:
            - "1313:1313"

    nodejs:
        build: .
        working_dir: /src
        environment:
            - NODE_ENV=development
            - NODE_PORT=8000
        volumes:
            - '.:/src'
        command: ["npm", "ci"]
